  
    
--------------------------------------------------------
--  DDL for Table SYS_MESSAGE
--------------------------------------------------------

  CREATE TABLE SYS_MESSAGE
   (	MESSAGE_UUID VARCHAR(100) NOT NULL,
        MESSAGE_KEY VARCHAR(13) NOT NULL,
	MESSAGE_VALUE VARCHAR(1024),
	CATEGORY_ENUM VARCHAR(13),
	LANGUAGE VARCHAR(10),
	IS_DELETED VARCHAR(1) DEFAULT '0', 	
	DATE_CREATE TIMESTAMP NOT NULL,
	CREATE_BY VARCHAR(50), 
	DATE_UPDATE TIMESTAMP,
	UPDATE_BY VARCHAR(50)
   );  
  
  
  ALTER TABLE SYS_MESSAGE ADD CONSTRAINT SYS_MESSAGE_PK PRIMARY KEY (MESSAGE_UUID);
  
  commit;

