
--------------------------------------------------------
--  DDL for Table SYS_CHANNEL
--------------------------------------------------------

  CREATE TABLE SYS_CHANNEL 
   (CHANNEL_UUID VARCHAR(100) NOT NULL, 
	NAME_MESSAGE_KEY VARCHAR(13) NOT NULL, 
	CHANNEL_ID INT NOT NULL,
	IS_DELETED VARCHAR(1) DEFAULT '0', 	
	DATE_CREATE TIMESTAMP NOT NULL,
	CREATE_BY VARCHAR(50), 
	DATE_UPDATE TIMESTAMP,
	UPDATE_BY VARCHAR(50)
   );
 
  
  ALTER TABLE SYS_CHANNEL ADD CONSTRAINT SYS_CHANNEL_PK PRIMARY KEY (CHANNEL_UUID);
  
    commit;
