--------------------------------------------------------
--  File created - Monday-June-23-2014   
--------------------------------------------------------

INSERT INTO SYS_CHANNEL (CHANNEL_UUID,CHANNEL_ID,NAME_MESSAGE_KEY,IS_DELETED,DATE_CREATE,CREATE_BY) SELECT UUID(),1,'SYSCHLIntel','0',CURRENT_TIMESTAMP,'System' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SYS_CHANNEL m WHERE  m.NAME_MESSAGE_KEY = 'SYSCHLIntel');
INSERT INTO SYS_CHANNEL (CHANNEL_UUID,CHANNEL_ID,NAME_MESSAGE_KEY,IS_DELETED,DATE_CREATE,CREATE_BY) SELECT UUID(),2,'SYSCHLIpad','0',CURRENT_TIMESTAMP,'System' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SYS_CHANNEL m WHERE  m.NAME_MESSAGE_KEY = 'SYSCHLIpad');

  commit;
