INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'UNKNOWN LANGUAGE','++','+++','+++','ARCLanguage++','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='++');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ARABIC','ar','ara','ara','ARCLanguageAR','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ar');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'CHINESE','zh','chi','zho','ARCLanguageZH','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='zh');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'DUTCH','nl','dut','nld','ARCLanguageNL','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='nl');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ENGLISH','en','eng','eng','ARCLanguageEN','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='en');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'FRENCH','fr','fre','fra','ARCLanguageFR','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='fr');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'GERMAN','de','ger','deu','ARCLanguageDE','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='de');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ITALIAN','it','ita','ita','ARCLanguageIT','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='it');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SPANISH','es','spa','spa','ARCLanguageES','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='es');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'AFAR','aa','aar','aar','ARCLanguageAA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='aa');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ABKHAZIAN','ab','abk','abk','ARCLanguageAB','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ab');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'AFRIKAANS','af','afr','afr','ARCLanguageAF','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='af');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'AMHARIC','am','amh','amh','ARCLanguageAM','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='am');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ASSAMESE','as','asm','asm','ARCLanguageAS','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='as');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'AYMARA','ay','aym','aym','ARCLanguageAY','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ay');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'AZERBAIJANI','az','aze','aze','ARCLanguageAZ','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='az');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'BASHKIR','ba','bak','bak','ARCLanguageBA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ba');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'BRETON','br','bre','bre','ARCLanguageBR','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='br');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'BYELORUSSIAN','be','bel','bel','ARCLanguageBE','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='be');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'BULGARIAN','bg','bul','bul','ARCLanguageBG','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='bg');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'BIHARI','bh','bih','bih','ARCLanguageBG','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='bh');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'BISLAMA','bi','bis','bis','ARCLanguageBI','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='bi');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'BENGALI','bn','ben','ben','ARCLanguageBN','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='bn');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TIBETAN','bo','bod','tib','ARCLanguageBO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='bo');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'CATALAN','ca','cat','cat','ARCLanguageCA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ca');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'CORSICAN','co','cos','cos','ARCLanguageCO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='co');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'CZECH','cs','ces','cze','ARCLanguageCS','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='cs');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'WELSH','cy','cym','wel','ARCLanguageCY','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='cy');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'DANISH','da','dan','dan','ARCLanguageCY','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='da');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'DZONGKHA','dz','dzo','dzo','ARCLanguageDZ','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='dz');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'GREEK, MODERN (1453-)','el','ell','gre','ARCLanguageEL','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='el');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ESPERANTO','eo','epo','epo','ARCLanguageEO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='eo');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ESTONIAN','et','est','est','ARCLanguageET','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='et');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'BASQUE','eu','baq','eus','ARCLanguageEU','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='eu');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'PERSIAN','fa','fas','per','ARCLanguageFA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='fa');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'FINNISH','fi','fin','fin','ARCLanguageFI','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='fi');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'FIJIAN','fj','fij','fij','ARCLanguageFJ','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='fj');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'FAROESE','fo','fao','fao','ARCLanguageFO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='fo');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'FRISIAN','fy','fry','fry','ARCLanguageFY','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='fy');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'IRISH','ga','gai','iri','ARCLanguageGA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ga');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'GALLEGAN','gl','glg','glg','ARCLanguageGL','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='gl');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'GUARANI','gn','grn','grn','ARCLanguageGN','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='gn');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'GUJARATI','gu','guj','guj','ARCLanguageGU','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='gu');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'HAUSA','ha','hau','hau','ARCLanguageHA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ha');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'HEBREW','he','heb','heb','ARCLanguageHE','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='he');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'HINDI','hi','hin','hin','ARCLanguageHI','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='hi');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'HUNGARIAN','hu','hun','hun','ARCLanguageHU','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='hu');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ARMENIAN','hy','arm','hye','ARCLanguageHY','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='hy');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'INTERLINGUA (INTERNATIONAL AUXILIARY LANGUAGE ASSOCIATION)','ia','ina','ina','ARCLanguageIA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ia');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'INDONESIAN','id','ind','ind','ARCLanguageID','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='id');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'INUPIAK','ik','ipk','ipk','ARCLanguageIK','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ik');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ICELANDIC','is','ice','isl','ARCLanguageIS','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='is');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'INUKTITUT','iu','iku','iku','ARCLanguageIU','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='iu');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'JAPANESE','ja','jpn','jpn','ARCLanguageJA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ja');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'JAVANESE','jv','jav','jaw','ARCLanguageJV','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='jv');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'GEORGIAN','ka','geo','kat','ARCLanguageKA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ka');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'KAZAKH','kk','kaz','kaz','ARCLanguageKK','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='kk');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'GREENLANDIC','kl','kal','kal','ARCLanguageKL','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='kl');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'KHMER','km','khm','khm','ARCLanguageKM','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='km');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'KANNADA','kn','kan','kan','ARCLanguageKN','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='kn');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'KOREAN','ko','kor','kor','ARCLanguageKO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ko');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'KASHMIRI','ks','kas','kas','ARCLanguageKS','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ks');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'KURDISH','ku','kur','kur','ARCLanguageKU','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ku');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'KIRGHIZ','ky','kir','kir','ARCLanguageKY','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ky');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'LATIN','la','lat','lat','ARCLanguageLA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='la');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'LINGALA','ln','lin','lin','ARCLanguageLN','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ln');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'LAO','lo','lao','lao','ARCLanguageLO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='lo');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'LITHUANIAN','lt','lit','lit','ARCLanguageLT','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='lt');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'LATVIAN','lv','lav','lav','ARCLanguageLV','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='lv');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'MALAGASY','mg','mlg','mlg','ARCLanguageMG','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='mg');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'MAORI','mi','mao','mri','ARCLanguageMI','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='mi');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'MACEDONIAN','mk','mac','mak','ARCLanguageMK','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='mk');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'MALTESE','ml','mlt','mlt','ARCLanguageML','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ml');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'MONGOLIAN','mn','mon','mon','ARCLanguageMN','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='mn');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'MOLDAVIAN','mo','mol','mol','ARCLanguageMO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='mo');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'MARATHI','mr','mar','mar','ARCLanguageMR','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='mr');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'MALAY','ms','may','msa','ARCLanguageMS','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ms');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'BURMESE','my','bur','mya','ARCLanguageMY','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='my');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'NAURU','na','nau','nau','ARCLanguageNA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='na');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'NEPALI','ne','nep','nep','ARCLanguageNE','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ne');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'NORWEGIAN','no','nor','nor','ARCLanguageNO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='no');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'LANGUE D''OC (POST 1500)','oc','oci','oci','ARCLanguageOC','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='oc');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'OROMO','om','orm','orm','ARCLanguageOM','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='om');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ORIYA','or','ori','ori','ARCLanguageOR','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='or');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'PANJABI','pa','pan','pan','ARCLanguagePA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='pa');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'POLISH','pl','pol','pol','ARCLanguagePL','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='pl');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'PUSHTO','ps','pus','pus','ARCLanguagePS','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ps');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'PORTUGUESE','pt','por','por','ARCLanguagePT','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='pt');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'QUECHUA','qu','que','que','ARCLanguageQU','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='qu');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'RHAETO-ROMANCE','rm','roh','roh','ARCLanguageRM','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='rm');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'RUNDI','rn','run','run','ARCLanguageRN','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='rn');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ROMANIAN','ro','ron','rum','ARCLanguageRO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ro');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'RUSSIAN','ru','rus','rus','ARCLanguageRU','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ru');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'KINYARWANDA','rw','kin','kin','ARCLanguageRW','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='rw');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SANSKRIT','sa','san','san','ARCLanguageSA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sa');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SINDHI','sd','snd','snd','ARCLanguageSD','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sd');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SANGO','sg','sag','sag','ARCLanguageSG','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sg');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SERBO-CROATIAN','sh','scr','scr','ARCLanguageSH','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sh');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SINGHALESE','si','sin','sin','ARCLanguageSI','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='si');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SLOVAK','sk','slk','slo','ARCLanguageSK','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sk');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SLOVENIAN','sl','slv','slv','ARCLanguageSL','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sl');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SAMOAN','sm','smo','smo','ARCLanguageSM','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sm');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SHONA','sn','sna','sna','ARCLanguageSN','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sn');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SOMALI','so','som','som','ARCLanguageSO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='so');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ALBANIAN','sq','alb','sqi','ARCLanguageSQ','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sq');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SERBIAN','sr','scc','srp','ARCLanguageSR','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sr');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SISWANT','ss','ssw','ssw','ARCLanguageSS','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ss');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SOTHO, SOUTHERN','st','sot','sot','ARCLanguageST','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='st');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SUDANESE','su','sun','sun','ARCLanguageSU','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='su');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SWEDISH','sv','sve','swe','ARCLanguageSV','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sv');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'SWAHILI','sw','swa','swa','ARCLanguageSW','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='sw');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TAMIL','ta','tam','tam','ARCLanguageTA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ta');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TELUGU','te','tel','tel','ARCLanguageTE','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='te');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TAJIK','tg','tgk','tgk','ARCLanguageTG','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='tg');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'THAI','th','tha','tha','ARCLanguageTH','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='th');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TIGRINYA','ti','tir','tir','ARCLanguageTI','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ti');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TURKMEN','tk','tuk','tuk','ARCLanguageTK','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='tk');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TAGALOG','tl','tgl','tgl','ARCLanguageTL','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='tl');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TSWANA','tn','tsn','tsn','ARCLanguageTN','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='tn');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TONGA (NYASA)','to','tog','tog','ARCLanguageTO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='to');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TURKISH','tr','tur','tur','ARCLanguageTR','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='tr');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TSONGA','ts','tso','tso','ARCLanguageTS','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ts');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TATAR','tt','tat','tat','ARCLanguageTT','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='tt');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'TWI','tw','twi','twi','ARCLanguageTT','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='tw');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'UIGHUR','ug','uig','uig','ARCLanguageUG','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ug');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'UKRAINIAN','uk','ukr','ukr','ARCLanguageUK','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='uk');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'URDU','ur','urd','urd','ARCLanguageUR','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='ur');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'UZBEK','uz','uzb','uzb','ARCLanguageUZ','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='uz');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'VIETNAMESE','vi','vie','vie','ARCLanguageVI','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='vi');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'VOLAPÜK','vo','vol','vol','ARCLanguageVO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='vo');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'WOLOF','wo','wol','wol','ARCLanguageWO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='wo');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'XHOSA','xh','xho','xho','ARCLanguageXH','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='xh');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'YIDDISH','yi','yid','yid','ARCLanguageYI','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='yi');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'YORUBA','yo','yor','yor','ARCLanguageYO','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='yo');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ZHUANG','za','zha','zha','ARCLanguageZA','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='za');

INSERT INTO SYS_LANGUAGE_CODE(LANGUAGE_CODE_UUID,DESCRIPTION,ISO_ALPHA_2CD,ISO_ALPHA_3BCD,ISO_ALPHA_3TCD,NAME_MSG_KEY,
CREATE_BY,DATE_CREATE,UPDATE_BY,DATE_UPDATE,IS_DELETED)
 SELECT UUID(),'ZULU','zu','zul','zul','ARCLanguageZU','SYSUSER', CURRENT_DATE, 'SYSUSER', CURRENT_DATE, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM SYS_LANGUAGE_CODE WHERE ISO_ALPHA_2CD='zu');

commit;
